# Generated by Django 2.0 on 2017-12-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, db_column='dt_criacao', verbose_name='initial date')),
                ('name', models.CharField(blank=True, db_column='name', db_index=True, max_length=50, null=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, db_column='email', max_length=70, null=True, verbose_name='e-mail')),
                ('mensagem', models.TextField(blank=True, db_column='mensagem', max_length=300, null=True, verbose_name='description')),
                ('status', models.BooleanField(db_column='status', default=False, verbose_name='status')),
                ('ipaddress', models.CharField(blank=True, db_column='ipaddress', max_length=100, null=True, verbose_name='your IP Address')),
                ('dt_atualiz', models.DateTimeField(auto_now=True, db_column='dt_atualiz', null=True, verbose_name='updated date')),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=25, null=True, verbose_name='phone')),
                ('compayname', models.CharField(blank=True, db_column='companyname', db_index=True, max_length=50, null=True, verbose_name='companyname')),
                ('cnpjcpf', models.CharField(blank=True, db_column='cnpjcpf', db_index=True, max_length=25, null=True, verbose_name='cnpjcpf')),
                ('subject', models.CharField(blank=True, choices=[('Business', 'Business'), ('CoursePythonI', 'Course: Python I'), ('CoursePythonOOP', 'Course: Python OOP'), ('CourseMktDigital', 'Course: Mkt Digital'), ('CourseBasis', 'Course: Basis'), ('Q&A', 'Q&A'), ('R&S', 'R&S')], db_column='subject', db_index=True, default=6, max_length=20, null=True, verbose_name='subject')),
                ('paymentmethod', models.CharField(blank=True, choices=[('1', 'select an option...'), ('2', 'a vista com transferência bancária'), ('3', 'a vista com boleto bancário'), ('4', 'em 3X com boleto bancário')], db_column='paymentmethod', db_index=True, max_length=20, null=True, verbose_name='paymentmethod')),
                ('agree_term_participation_privacy_SN', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], db_column='agree_term_participation_privacy_SN', db_index=True, default=1, max_length=1, null=True, verbose_name='agree_term_participation_privacy_SN')),
            ],
            options={
                'verbose_name_plural': 'Contatos',
                'ordering': ['-dt_criacao', 'mensagem'],
            },
        ),
    ]
